#!/bin/bash
# Quick reference guide for running the optimized scraper

echo "=========================================="
echo "DealNews Scraper - Quick Start Guide"
echo "=========================================="
echo ""
echo "1️⃣  START SCRAPER (Optimized - Recommended)"
echo "   ./start_scraper_optimized.sh"
echo ""
echo "2️⃣  CHECK STATUS"
echo "   ps -p \$(cat scraper.pid)"
echo ""
echo "3️⃣  VIEW ERRORS ONLY"
echo "   tail -f error.log"
echo ""
echo "4️⃣  STOP SCRAPER"
echo "   kill \$(cat scraper.pid)"
echo ""
echo "=========================================="
echo "Features:"
echo "✅ Minimal logging (95% reduction)"
echo "✅ Runs in background"
echo "✅ Survives terminal close"
echo "✅ Auto-cleans old logs"
echo "✅ Maximum performance"
echo "=========================================="
